server:
  port: '3036'
spring:
  main:
    allow-bean-definition-overriding: true
userConfig:
  botNames: ''
  qqList: ''
  pwList: ''
  ownerQQ: ''
  adminQQ: ''
  testGroup: ''
scheduled:
  biliJob: 0 */5 * * * ?
  birthdayJob: 0 0 8 */1 * ?
  lookWorldJob: 0 30 7 */1 * ?
  updateJob: 0 */10 * * * ?
  exterminateJob: 0 0 17 ? * 7
  cleanJob: 0 0 4 */1 * ?
  dayJob: 0 0 0 */1 * ?
  picJob: 0 0 1 */1 * ?
  monthJob: 0 0 0 1 * ?
baiduIdentifyConfig:
  APP_ID: ''
  API_KEY: ''
  SECRET_KEY: ''
baiduAuditConfig:
  APP_ID: ''
  API_KEY: ''
  SECRET_KEY: ''
APIConfig:
  token: ''
